#!/bin/bash

result=$(nmcli -t -f type,state,connection d | egrep "^(tun|tap):connected" | awk -F':' '{ print $3 }')
[[ -z $result ]] && echo -e 'N/A\nN/A\n#cc241d' || echo -e "$result\n$result\n#458588"
