#!/bin/bash
# vim: filetype=sh

#FILENAME: volume-display.sh
#REQUIRES FONTAWESOME

mute=`amixer -D pulse | grep "Front Left: Play" | awk '{print $6}'`

if [ $mute == "[on]" ]; then
	vol=`amixer -D pulse | grep "Front Left: Play" | awk '{print $5}' | tr -d '[]' | tr -d '%'`
	if [ $vol == "0" ]; then
		echo " 0"
	elif [ $vol -gt 49 ]; then
		echo "  "$vol
	elif [ $vol -lt 50 ]; then
		echo "  "$vol
	fi
else
	echo -e "  Muted\nMuted\n#cc241d"
fi
