export TERM="xterm-256color"
source ~/.antigenrc

ENABLE_CORRECTION="true"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

alias startvpn="sudo openvpn --config /etc/openvpn/client/US_West.conf --writepid /run/openvpn-client/west.pid --daemon"
alias stopvpn="sudo killall openvpn"
alias restartvpn="stopvpn;startvpn"

alias vim="nvim"
alias git="hub"
alias up="cd ../"
alias bell="echo -e '\a'"
alias ls="ls --group-directories-first --color=auto -1"

alias rangercd="ranger --choosedir=$HOME/.config/rangerdir; cd $(cat $HOME/.config/rangerdir)"

alias poly="rlwrap poly"

alias hdmi="xrandr --output HDMI1 --auto --primary --output eDP1 --auto --pos 3840x540"

source /etc/environment

export XDG_CONFIG_HOME="$HOME/.config"
export EDITOR="nvim"

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/heroku/bin:$PATH
export PATH=/home/anthony/.config/nvim/plugged/vim-live-latex-preview/bin:$PATH
export PATH=/home/anthony/.gem/ruby/2.5.0/bin:$PATH
export PATH=/home/anthony/.nvm/versions/node/v6.11.1/bin:$PATH
export PATH=/home/anthony/.local/bin:$PATH
export PATH=/home/anthony/go/bin:$PATH

export SPOTIPY_CLIENT_ID="489201485d514813bca094694cfee09d"
export SPOTIPY_CLIENT_SECRET="477549bf4b8a4875b0b82279148e71b8"
export SPOTIPY_REDIRECT_URI="https://mysite.com/callback/"
export YOUTUBE_DEV_KEY="AIzaSyDS7h3GZKL5f-IjamrYzZsqDgO9XR96amE"

[ -f ~/.config/zsh/fzf.zsh ] && source ~/.config/zsh/fzf.zsh
#source /usr/share/nvm/init-nvm.sh

#source ~/.antigen/bundles/Valiev/almostontop/almostontop.plugin.zsh

source /usr/share/nvm/init-nvm.sh

source ~/.fonts/*.sh

#eval "$(fasd --init auto)"
alias v='f -e nvim'

function mkcd () {
    mkdir $1
    cd $1
}

function vs () {
    j $1
    code .
    exit
}

source /usr/share/autojump/autojump.zsh

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /home/anthony/.nvm/versions/node/v8.4.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/anthony/.nvm/versions/node/v8.4.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /home/anthony/.nvm/versions/node/v8.4.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /home/anthony/.nvm/versions/node/v8.4.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
