source ~/.antigenrc

ENABLE_CORRECTION="true"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs os_icon time)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

alias spotify="LD_PRELOAD=/usr/lib/libcurl.so.3:~/.config/spotifywm.so /usr/share/spotify/spotify &"
alias vim="nvim"
alias git="hub"
alias up="cd ../"

alias rangercd="ranger --choosedir=$HOME/.config/rangerdir; cd $(cat $HOME/.config/rangerdir)"

source /etc/environment

export XDG_CONFIG_HOME="$HOME/.config"
export EDITOR="nvim"

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/heroku/bin:$PATH
export PATH=/home/anthony/.config/nvim/plugged/vim-live-latex-preview/bin:$PATH
export PATH=/home/anthony/.gem/ruby/2.4.0/bin:$PATH

export SPOTIPY_CLIENT_ID="489201485d514813bca094694cfee09d"
export SPOTIPY_CLIENT_SECRET="477549bf4b8a4875b0b82279148e71b8"
export SPOTIPY_REDIRECT_URI="https://mysite.com/callback/"
export YOUTUBE_DEV_KEY="AIzaSyDS7h3GZKL5f-IjamrYzZsqDgO9XR96amE"

[ -f ~/.config/zsh/fzf.zsh ] && source ~/.config/zsh/fzf.zsh
source /usr/share/nvm/init-nvm.sh

source ~/.antigen/bundles/Valiev/almostontop/almostontop.plugin.zsh

source ~/.fonts/*.sh

function mkcd () {
    mkdir $1
    cd $1
}
